export default [
    {
        name: 'Elizabeth Warren',
        id: 'ewarren',
        state: 'Massachusetts',
        campaignSlogan: 'Win With Warren',
        status: 'declared',
        headshotImage: 'warren.png',
        polling: 9,
    },
    {
        name: 'Kirsten Gillibrand',
        id: 'kgillibrand',
        state: 'New York',
        campaignSlogan: 'Brave Wins',
        status: 'declared',
        headshotImage: 'gillibrand.png',
        polling: 1,
    },
    {
        name: 'Julian Castro',
        id: 'jcastro',
        state: 'Texas',
        campaignSlogan: 'One Nation, One Destiny',
        status: 'declared',
        headshotImage: 'castro.png',
        polling: 1,
    },
    {
        name: 'Tulsi Gabbard',
        id: 'tgabbard',
        state: 'Hawaii',
        campaignSlogan: 'Lead With Love',
        status: 'declared',
        headshotImage: 'gabbard.png',
        polling: 1,
    },
    {
        name: 'Kamala Harris',
        id: 'kharris',
        state: 'California',
        campaignSlogan: 'For The People',
        status: 'declared',
        headshotImage: 'harris.png',
        polling: 7,
    },
    {
        name: 'Andrew Yang',
        id: 'ayang',
        state: 'New York',
        campaignSlogan: 'Humanity First',
        status: 'declared',
        headshotImage: 'yang.png',
        polling: 2,
    },
    {
        name: 'Pete Buttigieg',
        id: 'pbuttigieg',
        state: 'Indiana',
        campaignSlogan: 'A Fresh Start for America',
        status: 'declared',
        headshotImage: 'buttigieg.png',
        polling: 8,
    },
    {
        name: 'Michael E. Arth',
        id: 'mearth',
        state: 'Florida',
        campaignSlogan: 'Michael E. Arth for President',
        status: 'declared',
        headshotImage: 'arth.png',
        polling: -1,
    },
    {
        name: 'Marianne Williamson',
        id: 'mwilliamson',
        state: 'Texas',
        campaignSlogan: 'Join the Evolution!',
        status: 'declared',
        headshotImage: 'williamson.png',
        polling: -1,
    },
    {
        name: 'Corey Booker',
        id: 'cbooker',
        state: 'New Jersey',
        campaignSlogan: 'We Rise',
        status: 'declared',
        headshotImage: 'booker.png',
        polling: 3,
    },
    {
        name: 'Amy Klobuchar',
        id: 'aklobuchar',
        state: 'Minnesota',
        campaignSlogan: 'Amy For America',
        status: 'declared',
        headshotImage: 'klobuchar.png',
        polling: 2,
    },
    {
        name: 'Bernie Sanders',
        id: 'bernie',
        state: 'Vermont',
        campaignSlogan: 'Not Me. Us.',
        status: 'declared',
        headshotImage: 'bernie.png',
        polling: 22,
    },
    {
        name: 'Bill De Blasio',
        id: 'bdeblasio',
        state: 'New York',
        campaignSlogan: '',
        status: 'undeclared',
        headshotImage: 'deblasio.png',
        polling: -1,
    },
    {
        name: 'Steve Bullock',
        id: 'sbullock',
        state: 'Montana',
        campaignSlogan: '',
        status: 'undeclared',
        headshotImage: 'bullock.png',
        polling: -1,
    },
    {
        name: 'Stacey Abrams',
        id: 'sabrams',
        state: 'Georgia',
        campaignSlogan: '',
        status: 'undeclared',
        headshotImage: 'abrams.png',
        polling: -1,
    },
    {
        name: 'Richard Ojeda',
        id: 'rojeda',
        state: 'West Virginia',
        campaignSlogan: '',
        status: 'dropped',
        headshotImage: 'ojeda.png',
        polling: -1,
    },
    {
        name: 'John Hickenlooper',
        id: 'jhickenlooper',
        state: 'Colorado',
        campaignSlogan: 'Stand Tall With Us',
        status: 'declared',
        headshotImage: 'hickenlooper.png',
        polling: -1,
    },
    {
        name: 'Beto O\'Rourke',
        id: 'borourke',
        state: 'Texas',
        campaignSlogan: 'We\'re All In This Together',
        status: 'declared',
        headshotImage: 'orourke.png',
        polling: 5,
    },
    {
        name: 'Wayne Messam',
        id: 'wmessam',
        state: 'Florida',
        campaignSlogan: 'Wayne for America',
        status: 'declared',
        headshotImage: 'messam.png',
        polling: -1,
    },
    {
        name: 'Tim Ryan',
        id: 'tryan',
        state: 'Ohio',
        campaignSlogan: 'Tim Ryan for America',
        status: 'declared',
        headshotImage: 'ryan.png',
        polling: 1,
    },
    {
        name: 'Mike Gravel',
        id: 'mgravel',
        state: 'Alaska',
        campaignSlogan: 'End the American Empire',
        status: 'declared',
        headshotImage: 'gravel.png',
        polling: -1,
    },
    {
        name: 'Michael Bennet',
        id: 'mbennet',
        state: 'Colorado',
        campaignSlogan: 'Michael Bennet for President',
        status: 'declared',
        headshotImage: 'bennet.png',
        polling: -1,
    },
    {
        name: 'Eric Swalwell',
        id: 'eswalwell',
        state: 'California',
        campaignSlogan: 'Go Big, Be Bold, and Do Good',
        status: 'declared',
        headshotImage: 'swalwell.png',
        polling: -1,
    },
    {
        name: 'Joe Biden',
        id: 'jbiden',
        state: 'Pennsylvania',
        campaignSlogan: 'Our Best Days Still Lie Ahead.',
        status: 'declared',
        headshotImage: 'biden.png',
        polling: 36,
    },
    {
        name: 'Seth Moulton',
        id: 'smoulton',
        state: 'Massachusetts',
        campaignSlogan: 'Seth Moulton for America',
        status: 'declared',
        headshotImage: 'moulton.png',
        polling: -1,
    },
    {
        name: 'John Delaney',
        id: 'jdelaney',
        state: 'Maryland',
        campaignSlogan: 'Focus on the future',
        status: 'declared',
        headshotImage: 'delaney.png',
        polling: 1,
    },
    {
        name: 'Jay Inslee',
        id: 'jinslee',
        state: 'Washington',
        campaignSlogan: 'Focus on the future',
        status: 'declared',
        headshotImage: 'inslee.png',
        polling: 1,
    },
  ];